// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldCup.Api.Data;

#nullable disable

namespace WorldCup.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706110801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldCup.Api.Models.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("WorldCup.Api.Models.BracketMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachAId")
                        .HasColumnType("integer");

                    b.Property<int>("CoachBId")
                        .HasColumnType("integer");

                    b.Property<int>("MatchStateId")
                        .HasColumnType("integer");

                    b.Property<int>("RoundIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerCoachId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchStateId");

                    b.HasIndex("TournamentId");

                    b.ToTable("BracketMatches");
                });

            modelBuilder.Entity("WorldCup.Api.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DraftSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DraftSessionId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("WorldCup.Api.Models.DraftPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuctionBidAmount")
                        .HasColumnType("integer");

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<int>("DraftSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("PickedPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("PlacedSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScoutedSquadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasAuctionWin")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasSteal")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DraftSessionId");

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("WorldCup.Api.Models.DraftSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentTurnCoachId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCoaches")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomCode")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TurnTimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DraftSessions");
                });

            modelBuilder.Entity("WorldCup.Api.Models.MatchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MatchStateId")
                        .HasColumnType("integer");

                    b.Property<int>("Minute")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchStateId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("WorldCup.Api.Models.MatchState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachAId")
                        .HasColumnType("integer");

                    b.Property<int>("CoachBId")
                        .HasColumnType("integer");

                    b.Property<int>("FoulsA")
                        .HasColumnType("integer");

                    b.Property<int>("FoulsB")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSpectatable")
                        .HasColumnType("boolean");

                    b.Property<int>("Minute")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltiesA")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltiesB")
                        .HasColumnType("integer");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<int>("PossessionA")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreA")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreB")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsA")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsB")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubsRemainingA")
                        .HasColumnType("integer");

                    b.Property<int>("SubsRemainingB")
                        .HasColumnType("integer");

                    b.Property<int>("TacticA")
                        .HasColumnType("integer");

                    b.Property<int>("TacticB")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MatchStates");
                });

            modelBuilder.Entity("WorldCup.Api.Models.NationalSquad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsJackpot")
                        .HasColumnType("boolean");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tournament")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NationalSquads");
                });

            modelBuilder.Entity("WorldCup.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Defending")
                        .HasColumnType("integer");

                    b.Property<int>("Era")
                        .HasColumnType("integer");

                    b.Property<bool>("IsJackpot")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NationalSquadId")
                        .HasColumnType("integer");

                    b.Property<int>("Pace")
                        .HasColumnType("integer");

                    b.Property<int>("Passing")
                        .HasColumnType("integer");

                    b.Property<int>("Physical")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Shooting")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NationalSquadId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WorldCup.Api.Models.RosterSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInjured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("PlayerId");

                    b.ToTable("RosterSlots");
                });

            modelBuilder.Entity("WorldCup.Api.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("WorldCup.Api.Models.BracketMatch", b =>
                {
                    b.HasOne("WorldCup.Api.Models.MatchState", "MatchState")
                        .WithMany()
                        .HasForeignKey("MatchStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCup.Api.Models.Tournament", null)
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchState");
                });

            modelBuilder.Entity("WorldCup.Api.Models.Coach", b =>
                {
                    b.HasOne("WorldCup.Api.Models.DraftSession", "DraftSession")
                        .WithMany("Coaches")
                        .HasForeignKey("DraftSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftSession");
                });

            modelBuilder.Entity("WorldCup.Api.Models.DraftPick", b =>
                {
                    b.HasOne("WorldCup.Api.Models.DraftSession", null)
                        .WithMany("Picks")
                        .HasForeignKey("DraftSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorldCup.Api.Models.MatchEvent", b =>
                {
                    b.HasOne("WorldCup.Api.Models.MatchState", null)
                        .WithMany("Events")
                        .HasForeignKey("MatchStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorldCup.Api.Models.Player", b =>
                {
                    b.HasOne("WorldCup.Api.Models.NationalSquad", "NationalSquad")
                        .WithMany("Players")
                        .HasForeignKey("NationalSquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NationalSquad");
                });

            modelBuilder.Entity("WorldCup.Api.Models.RosterSlot", b =>
                {
                    b.HasOne("WorldCup.Api.Models.Coach", "Coach")
                        .WithMany("Roster")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCup.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WorldCup.Api.Models.Coach", b =>
                {
                    b.Navigation("Roster");
                });

            modelBuilder.Entity("WorldCup.Api.Models.DraftSession", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Picks");
                });

            modelBuilder.Entity("WorldCup.Api.Models.MatchState", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("WorldCup.Api.Models.NationalSquad", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("WorldCup.Api.Models.Tournament", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
